# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=40)),
                ('text', models.TextField(default=' ', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail_address', models.CharField(max_length=50)),
                ('country_name', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('deleted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail_address', models.CharField(max_length=50)),
                ('country_name', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('reserved_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('room_number', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_cleaned', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_occupied', models.BooleanField(default=False)),
                ('room_number', models.PositiveIntegerField(default=0)),
                ('room_name', models.CharField(max_length=40)),
                ('room_description', models.TextField(default=' ', max_length=800)),
                ('smoking', models.BooleanField(default=False)),
                ('max_people', models.PositiveIntegerField(default=1)),
                ('image', models.FileField(default='image/room_default.png', upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reservedroom',
            unique_together=set([('date', 'room_number')]),
        ),
    ]
