# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180318_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('date', models.DateField()),
                ('room_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
