# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
