# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservedroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservedroom',
            unique_together=set([('date', 'room_id')]),
        ),
    ]
