# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservedroom',
            old_name='room_id',
            new_name='room_number',
        ),
        migrations.AlterUniqueTogether(
            name='reservedroom',
            unique_together=set([('date', 'room_number')]),
        ),
    ]
