# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(default='image/room_default.png', upload_to='image/'),
        ),
    ]
