# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180418_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail_address', models.CharField(max_length=50)),
                ('country_name', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
