# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deletedreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedreservation',
            name='deleted_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 15, 8, 56, 979992, tzinfo=utc)),
        ),
    ]
