# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_deletedreservation_deleted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedreservation',
            name='deleted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
